version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: techstore-mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
    volumes:
      - mongo-data:/data/db
    networks:
      - techstore-network

  frontend:
    build:
      context: ./frontend
      args:
        REACT_APP_API_URL: http://localhost:5000
    ports:
      - "3000:3000"
    container_name: techstore-frontend
    depends_on:
      - backend
    networks:
      - techstore-network

  backend:
    build: ./backend
    ports:
      - "5000:5000"
    container_name: techstore-backend
    environment:
      - NODE_ENV=production
      - PORT=5000
      - MONGODB_URI=mongodb://admin:password123@mongodb:27017/techstore?authSource=admin
    depends_on:
      - mongodb
    networks:
      - techstore-network

volumes:
  mongo-data:

networks:
  techstore-network:
    driver: bridge